name: Test workshops that has testing steps

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**.test.ts"
      - "**.test.js"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "v22.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Perform tests
        run: npm run test
